### ISSUE TITLE
double-clicking kills at least part of the extension

### ISSUE THREAD

**Issue by boneskull** [ajmath/Syntaxtic#46]
becomes this:

![broken extension](http://content.screencast.com/users/chiller/folders/Jing/media/bec923bc-0267-4592-a9a6-4e4a9f784a11/00000107.png)

the line numbers remain but the highlighting disappears and the code is shown as raw text

**Comment by JDiPierro** [comment]
Is there a way to disable this from happening? I was trying to find where in the code does this to build a custom version without it... I hate it... I double click text all the time to select it.

**Comment by ajmath** [comment]
I'm not sure.  Haven't touched this code in a long time.  Feel free to contribute a PR

**Comment by JDiPierro** [comment]
I was hoping to do just that but I can't find anywhere in the code that could be doing this. When I double-click and the editor is opened I see that the `source` class is added to `div.syntaxhighlighter` but I can't see what's doing that.

**Comment by JDiPierro** [comment]
I figured it out! #62
