### ISSUE TITLE
Please don't flood the DevTools console

### ISSUE THREAD

**Issue by axelcostaspena** [ajmath/Syntaxtic#51]
I love this plugin but I must have it constantly disabled and enabling it when I need it, because it floods the DevTools console, and is the web developer workspace.

![image](https://cloud.githubusercontent.com/assets/2345716/10762039/8673b6b8-7cc4-11e5-8c08-b2e8ae90a809.png)

**Comment by ajmath** [comment]
Thanks for the feedback.  I don't really have the bandwidth to work on this right now but I'm very open to pull requests.
