### ISSUE TITLE
'Could not load JavaScript' when installing extension

### ISSUE THREAD

**Issue by mileszs** [ajmath/Syntaxtic#53]
I received the following error:
<img width="1675" alt="screenshot 2015-11-20 14 58 21" src="https://cloud.githubusercontent.com/assets/2425/11310396/550b977c-8f97-11e5-8843-ea18aa49e21c.png">

Having tried it a couple times, the JS file that causes the error is not always the same. `background.js` was mentioned once, too. 

Installing from source worked fine, but I can't seem to activate the plugin to use it, unfortunately. Am I doing anything incorrectly?

**Comment by zaaack** [comment]
I have the same problem, before the author upload the complete extension, we can only build the extension from source.

**Comment by ajmath** [comment]
Thanks for reporting this!  Sorry I didn't get to it sooner.  I wasn't able to reproduce the issue but I built a new release and verified that I could load it.  It should be available in the webstore within the hour.

**Comment by deiga** [comment]
@mileszs Is this still an issue?

**Comment by mileszs** [comment]
@deiga Everything seems to be working as expected installing from source as well as from the Chrome store. Thanks!
